### PR TITLE
Add basic components for Message and conversation classes

### PR DESCRIPTION
**Pull request by Zwatotem**
Serialization not included yet. I plan to research more on binary serialization of objects and possibly use this.

### CODE REVIEW

**Comment by HansMeinIgel** [comment]
Methods such as Conversation::getUsers should probably return the original collection (List) instead of ICollection. That way no casting is required when trying to do something like conversation.getUsers().Find(u => u.Name == userName).

Also imo Conversation::addMessage should't require passing the id of the message to be created as parameter. Instead the conversation should keep track of available ids and assign an unique one to each created message (sth like with ids of created conversations in ChatSystem in my branch).

**Review by HansMeinIgel — APPROVED** [review]
Seems good, as for methods not yet implemented they'll have to be coded eventually but for now it's probably time to merge it all together.

**Comment by Zwatotem** [comment]
> Seems good, as for methods not yet implemented they'll have to be coded eventually but for now it's probably time to merge it all together.

I've got a separate branch for them, I'll start working on it today.

**Comment by HansMeinIgel** [comment]
> > Seems good, as for methods not yet implemented they'll have to be coded eventually but for now it's probably time to merge it all together.
> 
> I've got a separate branch for them, I'll start working on it today.

And I'm going to start working on implementation of Client-/ServerChatSystem (created a new branch for it). Since they also have methods like 'getUpdates' maybe I'll leave those unimplemented for now.

**Pull request merged**
